server:
  port: 2001
spring:
  application:
    name: mrk-system
  # 配置中心
  cloud:
    # 注册中心配置
    nacos:
      discovery:
        server-addr: 124.222.46.195:8848
      config:
        server-addr: 124.222.46.195:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.46.195:3306/magic_repo_kit?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: apollotest
  # redis
  redis:
    ##redis 单机环境配置
    host: 124.222.46.195
    port: 6379
    password: apollotest
    database: 0
    ssl: false
  cache:
    type: redis
    redis:
      time-to-live: 1h #过期时间 1小时