server:
  port: 8001
spring:
  application:
    name: mrk-system
  # 配置中心
  cloud:
    # 注册中心配置
    nacos:
      discovery:
        server-addr: 124.222.46.195:8848
      config:
        server-addr: 124.222.46.195:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.222.46.195:3306/magic_repo_kit?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: apollotest
  # redis
  redis:
    ##redis 单机环境配置
    host: 124.222.46.195
    port: 6379
    password: apollotest
    database: 0
    ssl: false
  cache:
    type: redis
    redis:
      time-to-live: 1h #过期时间 1小时
# magicRepoKit服务配置
mrk:
  token:
    sing-key: mrkmrkisapowerfulmicroservicearchitectureupgradedandoptimizedfromacommercialproject
  auth:
    local:
      client-id: magicrepokit
      client-secret: magicrepokit
# 三方登录配置
justauth:
  cache:
    prefix: 'mrk:social:state:'
    type: redis
    timeout: 24h
  enabled: true
  type:
    GITEE:
      client-id: 0396203ae2b0c332f514dcbf752097f0a8a69bb6672eacc4b781be737b5aad68
      client-secret: b519097c0d81206e9a2db86154d574edc81ff50b87aa80b248d5593293ce21f0
      redirect-uri: https://mrk.auroralpixel.world/auth
      ignore-check-redirect-uri: true
    GITHUB:
      client-id: 53b541f7602d85d88cf0
      client-secret: 4fe37d5be18c24d4b2783438b24be0595616eb5a
      redirect-uri: https://mrk.auroralpixel.world/auth
      ignore-check-redirect-uri: true
    GOOGLE:
      client-id: 523371826852-0l0cips35vf8ss9mt7bbq7mnau1flngj.apps.googleusercontent.com
      client-secret: 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
      redirect-uri: https://mrk.auroralpixel.world/auth
      ignore-check-redirect-uri: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


  http-config:
    proxy:
      GITHUB:
        hostname: 127.0.0.1
        port: 7890
        type: HTTP
      GOOGLE:
        hostname: 127.0.0.1
        port: 7890
        type: HTTP
