server:
  port: 1000

spring:
  application:
    name: mrk-gateway
  cloud:
    # 注册中心配置
    nacos:
      discovery:
        server-addr: 124.222.46.195:8848
      config:
        server-addr: 124.222.46.195:8848
    gateway:
      discovery:
    # 允许通过服务名称进行路由转发访问， http://service-id/user
        locator:
          enabled: true
  # 路由配置
      routes:
#        - id: stock-user
#          uri: lb://stock-user
#          predicates:
#            - Path=/user/**
        - id: mrk-auth
          uri: lb://mrk-auth
          predicates:
            # - Method=GET,POST  不要开启此项
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: mrk-user
          uri: lb://mrk-system
          predicates:
            # - Method=GET,POST  不要开启此项
            - Path=/system/**
          filters:
            - StripPrefix=1
  # redis
  redis:
    ##redis 单机环境配置
    host: 124.222.46.195
    port: 6379
    password: apollotest
    database: 0
    ssl: false
# magicRepoKit服务配置
mrk:
  token:
    sing-key: mrkmrkisapowerfulmicroservicearchitectureupgradedandoptimizedfromacommercialproject