server:
  port: 9999
spring:
  application:
    name: mrk-auth
  # 配置中心
  cloud:
    # 注册中心配置
    nacos:
      discovery:
        server-addr: 124.222.46.195:8848
      config:
        server-addr: 124.222.46.195:8848