spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  cloud:
    client:
      ipAddress: 127.0.0.1

  freemarker:
    enabled: true
    suffix: .html
    request-context-attribute: rc
    content-type: text/html
    charset: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

  datasource:
    url: jdbc:mysql://124.222.46.195:3306/bladex?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: apollotest
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 1001
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
  servlet:
    context-path: /auth
  use-forward-headers: true

logging:
  level:
    root: debug
    org.springframework.web: info

eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      #eurekaServers
      defaultZone: http://127.0.0.1:2001/eureka

